name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for full history

      - name: Pull Blacklock Code Scanner Docker Image
        run: docker pull blacklock-code-scanner:latest

      - name: Run Blacklock Code Scanner
        run: |
          docker run --rm \
          -v $(pwd):/app \
          -e SONAR_PROJECTKEY="${{ secrets.PROJECTKEY }}" \
          -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
          -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          blacklock-code-scanner:latest
